### ISSUE TITLE
Why are two dots/icons needed?

### ISSUE THREAD

**Issue by FezVrasta** [Mortennn/Dozer#117] opened 2020-06-25 13:35 UTC
Why does the app need two icons/dots instead of just one? I think the most common use case (as shown in the README) is to move the two dots together and toggle anything on the left of them. But why do I need to have two dots rather than just one?

Could you add an option to hide the second one please?

**Comment by anukul** [comment] 2020-06-26 08:37
duplicate of https://github.com/Mortennn/Dozer/issues/113

**Closed** 2020-06-26 11:05 UTC
