### ISSUE TITLE
A slight CPU usage jump after updating to 3.0.5

### ISSUE THREAD

**Issue by mustafawm** [Mortennn/Dozer#65] opened 2019-04-16 10:33 UTC
Noticed Dozer started showing up on CPU top 5 consumers list (screen shot from iStats) after the last update (v 3.0.5) 

<img width="292" alt="Screen Shot 2019-04-16 at 8 25 58 pm" src="https://user-images.githubusercontent.com/13101565/56202391-3efa8380-6086-11e9-94c9-2dadead0e3d0.png">

> Not a significant deal though

**Comment by mustafawm** [comment] 2019-04-16 12:40
closing...not an issue.

**Comment by Wdavery** [comment] 2019-04-16 15:03
This should be reopened, definitely an issue for me as well.

**Comment by Mortennn** [comment] 2019-04-16 17:54
@Wdavery Does the problem persist if you restart Dozer?

**Comment by Wdavery** [comment] 2019-04-16 21:08
Does not persist.

**Comment by Mortennn** [comment] 2019-04-16 21:11
Great! The issue is related to the welcome screen not being closed properly. It will get fixed in the next release.

**Comment by mustafawm** [comment] 2019-04-16 21:14
Thanks @Mortennn 
You can close this once the fix is pushed.

**Comment by mustafawm** [comment] 2019-04-26 05:32
Also FYI https://dozermac.com still offers 3.0.4 version

**Comment by Mortennn** [comment] 2019-04-26 06:24
That's fixed now. Thank you 👍

**Comment by mustafawm** [comment] 2019-08-06 05:30
Hi @Mortennn  any update on this issue?

**Comment by Mortennn** [comment] 2019-08-06 14:37
In my testing, the issue is fixed in master.

Checkout [CONTRIBUTING.md](https://github.com/Mortennn/Dozer/blob/master/CONTRIBUTING.md#getting-started) on how to build Dozer.

I will close this issue once the new version of Dozer is released.

**Comment by mustafawm** [comment] 2019-08-07 12:18
Built and ran it for a while, seems to be working fine 👍

**Closed** 2019-09-05 17:32 UTC
