### ISSUE TITLE
I want to use click open | hidden 

### ISSUE THREAD

**Issue by Chasers9527** [Mortennn/Dozer#36] opened 2018-11-30 09:10 UTC
I want only use click to toggle bar status, Can you add this feature?

**Comment by Mortennn** [comment] 2018-11-30 10:37
I am not sure what you mean. Can you please elaborate?😀

**Comment by Chasers9527** [comment] 2018-12-01 02:51
![image](https://user-images.githubusercontent.com/16145443/49323403-e05cbf00-f555-11e8-8184-926be8e3813a.png)


when a click this button to toggle show or hidden Finder  Instead of clicking anywhere on menu bar 
can you add a choose 

![image](https://user-images.githubusercontent.com/16145443/49323408-fec2ba80-f555-11e8-8d9c-668eeab43e97.png)
click this button to toggle

![image](https://user-images.githubusercontent.com/16145443/49323410-08e4b900-f556-11e8-8c8a-407de7922c10.png)
not is click anywhere on menu bar

**Comment by Chasers9527** [comment] 2018-12-01 03:00
I have two monitors, one big and one small, and this problem occurs when I use them.

![toggle](https://user-images.githubusercontent.com/16145443/49323563-2a46a480-f558-11e8-98cd-a6803f122453.gif)

**Comment by Mortennn** [comment] 2018-12-01 11:38
Update to v2.2.1. The issue is fixed in that version.

**Closed** 2018-12-01 11:39 UTC
