### ISSUE TITLE
'Thanks for downloading' dialog window stuck

### ISSUE THREAD

**Issue by oswaldcameron** [Mortennn/Dozer#43] opened 2018-12-11 21:33 UTC
Clicking _Continue_ button does not close window. Restarting app just opens the window again.

Version 3.0.0

<img width="631" alt="dialog window" src="https://user-images.githubusercontent.com/9535290/49831679-81bbf000-fd62-11e8-8da8-1f03eac1d25b.png">

PS: Thank you! Love the app.

**Comment by 3zero2** [comment] 2018-12-11 21:38
Duplicate of issue #42

**Closed** 2018-12-12 19:36 UTC
