### ISSUE TITLE
Unhides after CMD-Tabbing between screens

### ISSUE THREAD

**Issue by orangefult** [Mortennn/Dozer#32] opened 2018-11-12 18:27 UTC
First off, this application is awesome, thank you for making it, and making it opensource!

The icons in the menubar unhide randomly, and not always, but it seems to do it when I CMD-Tab between screens and then click on another application. It could be related to #31 but it doesn't just happen when i'm on the menu bar.

**Comment by Mortennn** [comment] 2018-11-12 20:06
I will take a look at it soon. Thanks for reporting!

**Comment by Mortennn** [comment] 2018-11-17 17:02
I am not able to reproduce this issue. Does it happen often? If not, will it be okay if I close the issue?

**Comment by Rodziac** [comment] 2018-12-03 20:14
Hello! I really like this application too, but I came across a similar bug.

I can report that (at least on my setup) it is not much about CMD-tabbing but on my 3 screen setup while the icons are hidden if I click on a window or desktop on my third screen, the icons jump back on.

I can make a new issue if you do not think this is relevant to this one but since both our issues are from multi screen setups I thought this might help.

**Comment by Mortennn** [comment] 2018-12-03 20:38
I am on a 2 monitor setup, so this might be the reason why I have haven't been able to recreate this issue. And the issue is current in Dozer v2.2.2?

**Comment by Rodziac** [comment] 2018-12-03 21:11
> And the issue is current in Dozer v2.2.2?

Yes, I currently use v2.2.2.

**Comment by Mortennn** [comment] 2018-12-03 21:42
Alright, just wanted to make sure. I will investigate this issue as soon as possible.

**Comment by Kartal1903** [comment] 2018-12-10 16:36
I too am having this problem. I'm using just a second screen besides my macbook (not 3).
Thanks for making such an awesome app. Other than this issue it works like a charm for me.

**Comment by Mortennn** [comment] 2018-12-11 09:35
A fix will be released in about 2 days😀

**Comment by Kartal1903** [comment] 2018-12-11 14:33
Much appreciated!

**Comment by Mortennn** [comment] 2018-12-12 19:37
This should be fixed in v3.02. If not, just reopen the issue.

**Closed by Mortennn** 2018-12-12 19:37 UTC
