### ISSUE TITLE
Icons do not re-appear in Full Screen mode

### ISSUE THREAD

**Issue by 3zero2** [Mortennn/Dozer#39] opened 2018-12-05 16:25 UTC
Steps to reproduce:

1. Make sure that app icons are hidden
2. Open an app in full screen mode
3. Put cursor on top of screen to show the menubar.
4. Click on menubar to make icons appear

The result is that the icons do not appear. The click is registered but it only leads to the menu bar disappearing.

**Comment by Mortennn** [comment] 2018-12-05 17:45
When I do it the menu bar disappears, but the icons do appear. Do you use version 2.2.2?

![test](https://user-images.githubusercontent.com/34214574/49532438-c8ba6900-f8bc-11e8-9f86-828d53d39ed1.gif)

**Comment by 3zero2** [comment] 2018-12-05 18:08
Upon further investigation I found something interesting. This is on a Late 2013 MacBook Pro.

When using tap to click, this will make the menubar disappear and Dozer will not activate
When actually pressing the trackpad down (this does not have force touch), the action will make Dozer appear and then subsequently the menubar disappear - as per your recording.

I understand this is an edge case. However I can replicate this every time. If you need a screen recording let me know.

**Comment by Mortennn** [comment] 2018-12-05 19:13
I must be something to do with force touch because I am not able to reproduce this on a MacBook Pro with force touch. 
It would be nice if you could share a screen recording, just to make sure I am not missing anything.

**Comment by 3zero2** [comment] 2018-12-05 21:19
Thank you for the reply. The following screen recording was carried out using only tap to click.

![screen recording 2018-12-05 at 22 16 32](https://user-images.githubusercontent.com/6965396/49544648-a1bf5f80-f8db-11e8-8fde-7326ccfc018e.gif)

**Comment by Mortennn** [comment] 2018-12-06 10:01
I see. I will take a look at it soon. Thanks for reporting.

**Comment by Mortennn** [comment] 2018-12-11 20:41
@3zero2 The issue should be resolved in v3😀

**Closed by Mortennn** 2018-12-11 20:41 UTC
Labels: bug
